name: Check python versions using pipx and setup-python
on:
  workflow_dispatch:

jobs:
  pip_install_poetry:
    strategy:
      matrix:
        python-version: [3.7.8, 3.11.1]
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
            python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2
      - run: python --version
      - run: poetry --version
      - run: poetry run python --version

  pipx_install_poetry:
    strategy:
      matrix:
        python-version: [3.7.8, 3.11.1]
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
            python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v3
      - run: python --version
      - run: poetry --version
      - run: poetry run python --version
